# Generated by Django 3.2.5 on 2023-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0005_auto_20230218_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
